use python3.7 instead python3.5
wazo-platform/sf-config pull request #33
Opened 2019-10-09 18:30 UTC by fblackburn1

2019-10-10 08:05 UTC, fredericlepied requested changes
We don't have Python 3.7 on Debian Stretch and Centos 7...

2019-10-10 12:44 UTC, fblackburn1 commented
> We don't have Python 3.7 on Debian Stretch and Centos 7...

Oh so sad. 
So to understand correctly, these config are only for the software factory VM?
There are no impact on the tests or whatever others jobs?
If so we can close the PR

2019-10-11 10:38 UTC, sileht requested changes
I think none of these changes are needed.

2019-10-11 10:38 UTC, sileht commented on nodepool/runC/debian-stretch-rootfs.yaml
> +    {{ bwrap_command }} /bin/bash -lc "apt-get install -y openssh-server rsync iproute git python-pip python3-pip traceroute libpq-dev python2.7 libpython2.7-dev python-pkg-resources python3.7 libpyt
3.7 does not exists in stretch

2019-10-11 10:38 UTC, sileht commented on nodepool/elements/virt-customize/zuul.sh
> +    PKGS="rsync iproute git virtualenv python-pip python3-pip traceroute libpq-dev python2.7 libpython2.7-dev python-pkg-resources python-yaml python3.7 libpython3.7-dev python3-pkg-resources sudo do
3.7 does not exists in stretch

2019-10-11 10:38 UTC, sileht commented on playbooks/config/check.yaml
> +            env - /opt/rh/rh-python37/root/bin/repoxplorer-config-validate --config {{ config_root }}/defconf/defconf-repoxplorer.py
On software factory it's still 3.5

2019-10-11 12:09 UTC, fblackburn1 commented
Ok thanks

2019-10-11 12:09 UTC, closed without merging